---
title: "Structure of NTSPortal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Structure of NTSPortal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Index mappings (DB Schema)

ElasticSearch uses indices to store data. NTSPortal contains different index types, each with a different structure. 

The mapping code and field descriptions for the different tables: 

- [`dbas`](https://github.com/bafg-bund/ntsportal/tree/main/inst/mappings/dbas_index_mappings.json) (results of library screening data processing)
- [`msrawfiles`](https://github.com/bafg-bund/ntsportal/tree/main/inst/mappings/msrawfiles_index_mappings.json) (metadata and processing parameters for measurement files)
- [`analysis_dbas`](https://github.com/bafg-bund/ntsportal/tree/main/inst/mappings/analysis_dbas_index_mappings.json) (summary statistics for dbas)
- [`spectral_library`](https://github.com/bafg-bund/ntsportal/tree/main/inst/mappings/spectral_library_index_mappings.json) (copy of collective spectral library - CSL)

# Index naming conventions

The indices are named using the convention:  
`ntsp<version number>_index_<optional specification, e.g. 'analysis'>_<index type, e.g. 'dbas'>_v<ingest time  'YYMMDDHHmmSS'>_<project or institute, e.g. 'bfg'>`  
For example: `ntsp25.1_index_analysis_dbas_v240215101520_bfg`, `ntsp25.1_index_nts_v240316101520_lanuv`

There are defined codes for project or institute.

The exception is the msrawfiles index, since there is only one and there is no alias, this is just called `ntsp25.1_msrawfiles`.

Each other index type can have any number of indices, for a particular project, institute or other subset of data.

# Aliases

ElasticSearch uses aliases to make accessing an index easier. These names are designed to be shorter and not to change. They point to an index. The aliases have the following naming convention:  
`ntsp<version number>_<optional specification, e.g. 'analysis'>_<index type, e.g. 'dbas'>_<project or institute, e.g. 'bfg'>`  
For example: `ntsp25.1_dbas_bfg`

The alias will point to the current version of the index. This way, several versions of an index can be maintained concurrently for testing and backup purposes.

# Data views

Kibana uses data views to allow for granular data access rights. A data view is a name pattern potentially matching one or several indices (or aliases). A user has a role, and each role is given access to specific indices. The dashboards in Kibana are built with data views so that they are programmed only once and the users role determines which indices are visible in the dashboard. 

An example of a data view is: `ntsp25.1_dbas*`. This data view will access both the aliases `ntsp25.1_dbas_bfg` and `ntsp25.1_dbas_lanuv`, for example. So that a user with the role `ntsp_lanuv`, which has access to both aliases and therefore the linked indices, will see both datasets when viewing a dashboard visual using that data view. 

It is important that alias names are not a subset of each other or indices. So the `ntsp_is_dbas` alias is correct while `ntsp_dbas_is` is incorrect. This is because this second alias would also match the data view `ntsp_dbas*` and therefore the internal standard data would appear together with the results.  

The following table shows some examples of the naming conventions

|Index|Alias|Data view|Comment|
|-----|-----|---------|-------|
|ntsp25.1_index_dbas_v240418101520_bfg|ntsp25.1_dbas_bfg|ntsp25.1_dbas*||
|ntsp25.1_index_dbas_v240422101520_bfg|ntsp25.1_dbas_bfg|ntsp25.1_dbas*||
|ntsp25.1_spectral_library|-|ntsp25.1_spectral_library*|There is currently no institute/project specific library|
|ntsp25.1_index_analysis_dbas_v240418101520_upb|ntsp25.1_analysis_dbas_upb|ntsp25.1_analysis_dbas*||
|ntsp25.1_msrawfiles|-|ntsp25.1_msrawfiles*||
|ntsp25.1_index_is_dbas_v240218101520_bfg|ntsp25.1_is_dbas_bfg|ntsp25.1_is_dbas*||
|ntsp25.1_index_nts_v240428101520_unit_tests|ntsp25.1_nts_unit_tests|||
|ntsp25.1_index_test_dbas_v250408101520_bfg|ntsp25.1_test_dbas_bfg|ntsp25.1_test_dbas*|see kibanaIntegrationTests|


