---
title: "Measurement file naming conventions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Measurement file naming conventions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# BfG measurement file naming

- Filenames always use lowercase letters (a-z) because Windows ignores capitalization while Linux does not.
- Replicates are named `extrepX` or `injrepX` for extraction and injection replicates, respectively. X is a number 1-9.
- Parameters to insert are indicated with `<...>` all other text is fixed and must be copied exactly.
- Optional parameters are given additionally in square brackets `[...]`

## General parameter descriptions
- `<pol>`: polarity ("pos" or "neg")
- `<station>`: see station naming conventions
- `<composite type>`: Jahresmischprobe "jmp", Monatsmischprobe "mmp", Tagesmischprobe "tmp", Stichprobe "sp"  

## FRAME reference samples  
`<Messdatum YYYY-MM-DD>_frame_mix_<instrument>_<concentration>ngl[_injrep<X>]_<pol>`

`<instrument>`: "wasser_tof" or "sediment_tof"  
`<concentration>`: concentration in ng/L  
`<X>`: The replicate number (1-9) (one digit)  
 
Example: 
`2024-02-29_frame_mix_wasser_tof_1000ngl_injrep3_pos.wiff`

## ASE blanks  
`<Messdatum YYYY-MM-DD>_ase_bw_<XX>_e<Extraktionsdatum YYYY-MM-DD>_<pol>`

`<XX>`: Continuous numbering within same job (e.g. one year of composite samples of all stations) (01-99, 2 digits)  

Example:  
`2024-08-30_ase_bw_01_e2024-07-01_pos.wiff`
  
## ASE reference samples  
`<Messdatum YYYY-MM-DD>_ase_ref_<XXX>_e<Extraktionsdatum YYYY-MM-DD>_<pol>`  

`<XXX>`: Continuous numbering... forever (001-999, three digits) 

Example:  
`2024-08-30_ase_ref_001_e2024-07-01_pos.wiff`  
  
## Monthly and yearly composite SPM samples (umweltprobenbank)  
`<station>_<Probenamedatum YYYY / YYYY-MM>_<composite type>_extrep<X>_<pol>`

`<X>`: the replicate number (1-9, one digit)  

Example:  
`rhein_ko_l_2023_jmp_extrep1_pos.wiff`

## Daily composite samples water matrix (BfG stations)
`<station>_<Probenamedatum YYYY-MM-DD>_<composite type>[_injrep<X>]_<pol>`

`<X>`: The replicate number (1-9) (one digit)

Example:  
`rhein_ko_l_2025-01-13_tmp_pos.wiff`

## Old naming
**Old station naming for monatsmischproben**

| station | abbreviation|
|-------------|---------|
| Bimmen | bim |
| Dessau | des |
| Jochenstein | joc |
| Rehlingen | reh |
| Koblenz | kob |
| Weil | wei |
| Zehren | zeh |  

**Old naming system for annual composite samples:**  
'JJ' refers to the two digit year, 'X' to the replicate number.

| **station** | **datafiles** | **station name** | **folder name** |
|-------------|-----------------------|------------------|----------------|
| Barby | Bar_JJ_X_pol.\* | elbe_ba_m | elb_pol |
| Bimmen | BJJ_polX.\* | rhein_bi_l | rhb_pol |
| Blankenese | Bla_JJ_X_pol.\* | elbe_bl_m | elbl_pol |
| Cumlosen | Cum_JJ_XX_pol.\* | elbe_cu_m | elc_pol |
| Dessau | Des_JJ_XX_pol.\* | mulde_de_m | mud_pol |
| Güdingen | Gue_JJ_X_pol.\* | saar_gu_m | sag_pol |
| Iffezheim | IJJ_polX.\* | rhein_if_m | rhi_pol |
| Jochenstein | Joch_JJ_X_pol.\* | donau_jo_m | doj_pol |
| Koblenz | KO_JJ_X_pol.\* | rhein_ko_l | rhk_pol |
| Prossen | Pro_JJ_X_pol.\* | elbe_pr_r | elp_pol |
| Rehlingen | RJJ_polX.\* | saar_re_m | sar_pol |
| Ulm | Ulm_JJ_X_pol.\* | donau_ul_m | dou_pol |
| Weil | WJJ_polX.\* | rhein_we_r | rhw_pol |
| Wettin | Wett_JJ_X_pol.\* | saale_wettin_m | saw_pol |
| Zehren | Zeh_JJ_X_pol.\* | elbe_ze_l | elz_pol |

<!-- Copyright 2025 Bundesanstalt für Gewässerkunde -->
<!-- This file is part of ntsportal -->
